//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyCuaHang.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.8.1.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-BL0QFT1\\SQLEXPRESS01;Initial Catalog=cuahangcaycanh;Integrate" +
            "d Security=True")]
        public string cuahangcaycanhConnectionString {
            get {
                return ((string)(this["cuahangcaycanhConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-BL0QFT1\\SQLEXPRESS01;Initial Catalog=QuanLyCuaHang;Integrated" +
            " Security=True")]
        public string QuanLyCuaHangConnectionString {
            get {
                return ((string)(this["QuanLyCuaHangConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-V6PVQLN\\SQLEXPRESS;Initial Catalog=QLCH;Integrated Security=T" +
            "rue")]
        public string QLCHConnectionString {
            get {
                return ((string)(this["QLCHConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=BOBBY\\SQLEXPRESS;Initial Catalog=QuanLyCuaHang;Integrated Security=Tr" +
            "ue")]
        public string QuanLyCuaHangConnectionString1 {
            get {
                return ((string)(this["QuanLyCuaHangConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-V6PVQLN\\SQLEXPRESS;Initial Catalog=QuanLyCuaHang;Integrated S" +
            "ecurity=True")]
        public string QuanLyCuaHangConnectionString2 {
            get {
                return ((string)(this["QuanLyCuaHangConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-BL0QFT1\\SQLEXPRESS;Initial Catalog=QuanLyCuaHang;Integrated S" +
            "ecurity=True")]
        public string QuanLyCuaHangConnectionString3 {
            get {
                return ((string)(this["QuanLyCuaHangConnectionString3"]));
            }
        }
    }
}
