#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataConnect
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="cuahangcaycanh")]
	public partial class QLCHDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertchamcong(chamcong instance);
    partial void Updatechamcong(chamcong instance);
    partial void Deletechamcong(chamcong instance);
    partial void Inserthoadon(hoadon instance);
    partial void Updatehoadon(hoadon instance);
    partial void Deletehoadon(hoadon instance);
    partial void Insertchitiethoadon(chitiethoadon instance);
    partial void Updatechitiethoadon(chitiethoadon instance);
    partial void Deletechitiethoadon(chitiethoadon instance);
    partial void Insertkhachhang(khachhang instance);
    partial void Updatekhachhang(khachhang instance);
    partial void Deletekhachhang(khachhang instance);
    partial void Insertloaisanpham(loaisanpham instance);
    partial void Updateloaisanpham(loaisanpham instance);
    partial void Deleteloaisanpham(loaisanpham instance);
    partial void Insertnhanvien(nhanvien instance);
    partial void Updatenhanvien(nhanvien instance);
    partial void Deletenhanvien(nhanvien instance);
    partial void Insertsanpham(sanpham instance);
    partial void Updatesanpham(sanpham instance);
    partial void Deletesanpham(sanpham instance);
    partial void Inserttaikhoan(taikhoan instance);
    partial void Updatetaikhoan(taikhoan instance);
    partial void Deletetaikhoan(taikhoan instance);
    #endregion
		
		public QLCHDataContext() : 
				base(global::DataConnect.Properties.Settings.Default.cuahangcaycanhConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public QLCHDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLCHDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLCHDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLCHDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<chamcong> chamcongs
		{
			get
			{
				return this.GetTable<chamcong>();
			}
		}
		
		public System.Data.Linq.Table<hoadon> hoadons
		{
			get
			{
				return this.GetTable<hoadon>();
			}
		}
		
		public System.Data.Linq.Table<chitiethoadon> chitiethoadons
		{
			get
			{
				return this.GetTable<chitiethoadon>();
			}
		}
		
		public System.Data.Linq.Table<khachhang> khachhangs
		{
			get
			{
				return this.GetTable<khachhang>();
			}
		}
		
		public System.Data.Linq.Table<loaisanpham> loaisanphams
		{
			get
			{
				return this.GetTable<loaisanpham>();
			}
		}
		
		public System.Data.Linq.Table<nhanvien> nhanviens
		{
			get
			{
				return this.GetTable<nhanvien>();
			}
		}
		
		public System.Data.Linq.Table<sanpham> sanphams
		{
			get
			{
				return this.GetTable<sanpham>();
			}
		}
		
		public System.Data.Linq.Table<taikhoan> taikhoans
		{
			get
			{
				return this.GetTable<taikhoan>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.chamcong")]
	public partial class chamcong : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _manhanvien;
		
		private System.Nullable<decimal> _luong1ngay;
		
		private System.Nullable<int> _songaylam;
		
		private EntityRef<nhanvien> _nhanvien;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmanhanvienChanging(string value);
    partial void OnmanhanvienChanged();
    partial void Onluong1ngayChanging(System.Nullable<decimal> value);
    partial void Onluong1ngayChanged();
    partial void OnsongaylamChanging(System.Nullable<int> value);
    partial void OnsongaylamChanged();
    #endregion
		
		public chamcong()
		{
			this._nhanvien = default(EntityRef<nhanvien>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_manhanvien", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string manhanvien
		{
			get
			{
				return this._manhanvien;
			}
			set
			{
				if ((this._manhanvien != value))
				{
					if (this._nhanvien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmanhanvienChanging(value);
					this.SendPropertyChanging();
					this._manhanvien = value;
					this.SendPropertyChanged("manhanvien");
					this.OnmanhanvienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_luong1ngay", DbType="Money")]
		public System.Nullable<decimal> luong1ngay
		{
			get
			{
				return this._luong1ngay;
			}
			set
			{
				if ((this._luong1ngay != value))
				{
					this.Onluong1ngayChanging(value);
					this.SendPropertyChanging();
					this._luong1ngay = value;
					this.SendPropertyChanged("luong1ngay");
					this.Onluong1ngayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_songaylam", DbType="Int")]
		public System.Nullable<int> songaylam
		{
			get
			{
				return this._songaylam;
			}
			set
			{
				if ((this._songaylam != value))
				{
					this.OnsongaylamChanging(value);
					this.SendPropertyChanging();
					this._songaylam = value;
					this.SendPropertyChanged("songaylam");
					this.OnsongaylamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="nhanvien_chamcong", Storage="_nhanvien", ThisKey="manhanvien", OtherKey="manhanvien", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public nhanvien nhanvien
		{
			get
			{
				return this._nhanvien.Entity;
			}
			set
			{
				nhanvien previousValue = this._nhanvien.Entity;
				if (((previousValue != value) 
							|| (this._nhanvien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._nhanvien.Entity = null;
						previousValue.chamcong = null;
					}
					this._nhanvien.Entity = value;
					if ((value != null))
					{
						value.chamcong = this;
						this._manhanvien = value.manhanvien;
					}
					else
					{
						this._manhanvien = default(string);
					}
					this.SendPropertyChanged("nhanvien");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.hoadon")]
	public partial class hoadon : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _mahoadon;
		
		private System.Nullable<System.DateTime> _ngaylap;
		
		private string _nhanvienban;
		
		private string _khachhang;
		
		private EntitySet<chitiethoadon> _chitiethoadons;
		
		private EntityRef<khachhang> _khachhang1;
		
		private EntityRef<nhanvien> _nhanvien;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmahoadonChanging(string value);
    partial void OnmahoadonChanged();
    partial void OnngaylapChanging(System.Nullable<System.DateTime> value);
    partial void OnngaylapChanged();
    partial void OnnhanvienbanChanging(string value);
    partial void OnnhanvienbanChanged();
    partial void OnkhachhangChanging(string value);
    partial void OnkhachhangChanged();
    #endregion
		
		public hoadon()
		{
			this._chitiethoadons = new EntitySet<chitiethoadon>(new Action<chitiethoadon>(this.attach_chitiethoadons), new Action<chitiethoadon>(this.detach_chitiethoadons));
			this._khachhang1 = default(EntityRef<khachhang>);
			this._nhanvien = default(EntityRef<nhanvien>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mahoadon", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string mahoadon
		{
			get
			{
				return this._mahoadon;
			}
			set
			{
				if ((this._mahoadon != value))
				{
					this.OnmahoadonChanging(value);
					this.SendPropertyChanging();
					this._mahoadon = value;
					this.SendPropertyChanged("mahoadon");
					this.OnmahoadonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngaylap", DbType="Date")]
		public System.Nullable<System.DateTime> ngaylap
		{
			get
			{
				return this._ngaylap;
			}
			set
			{
				if ((this._ngaylap != value))
				{
					this.OnngaylapChanging(value);
					this.SendPropertyChanging();
					this._ngaylap = value;
					this.SendPropertyChanged("ngaylap");
					this.OnngaylapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nhanvienban", DbType="NChar(10)")]
		public string nhanvienban
		{
			get
			{
				return this._nhanvienban;
			}
			set
			{
				if ((this._nhanvienban != value))
				{
					if (this._nhanvien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnnhanvienbanChanging(value);
					this.SendPropertyChanging();
					this._nhanvienban = value;
					this.SendPropertyChanged("nhanvienban");
					this.OnnhanvienbanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_khachhang", DbType="NChar(10)")]
		public string khachhang
		{
			get
			{
				return this._khachhang;
			}
			set
			{
				if ((this._khachhang != value))
				{
					if (this._khachhang1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnkhachhangChanging(value);
					this.SendPropertyChanging();
					this._khachhang = value;
					this.SendPropertyChanged("khachhang");
					this.OnkhachhangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="hoadon_chitiethoadon", Storage="_chitiethoadons", ThisKey="mahoadon", OtherKey="hoadon")]
		public EntitySet<chitiethoadon> chitiethoadons
		{
			get
			{
				return this._chitiethoadons;
			}
			set
			{
				this._chitiethoadons.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="khachhang_hoadon", Storage="_khachhang1", ThisKey="khachhang", OtherKey="makhachhang", IsForeignKey=true)]
		public khachhang khachhang1
		{
			get
			{
				return this._khachhang1.Entity;
			}
			set
			{
				khachhang previousValue = this._khachhang1.Entity;
				if (((previousValue != value) 
							|| (this._khachhang1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._khachhang1.Entity = null;
						previousValue.hoadons.Remove(this);
					}
					this._khachhang1.Entity = value;
					if ((value != null))
					{
						value.hoadons.Add(this);
						this._khachhang = value.makhachhang;
					}
					else
					{
						this._khachhang = default(string);
					}
					this.SendPropertyChanged("khachhang1");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="nhanvien_hoadon", Storage="_nhanvien", ThisKey="nhanvienban", OtherKey="manhanvien", IsForeignKey=true)]
		public nhanvien nhanvien
		{
			get
			{
				return this._nhanvien.Entity;
			}
			set
			{
				nhanvien previousValue = this._nhanvien.Entity;
				if (((previousValue != value) 
							|| (this._nhanvien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._nhanvien.Entity = null;
						previousValue.hoadons.Remove(this);
					}
					this._nhanvien.Entity = value;
					if ((value != null))
					{
						value.hoadons.Add(this);
						this._nhanvienban = value.manhanvien;
					}
					else
					{
						this._nhanvienban = default(string);
					}
					this.SendPropertyChanged("nhanvien");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_chitiethoadons(chitiethoadon entity)
		{
			this.SendPropertyChanging();
			entity.hoadon1 = this;
		}
		
		private void detach_chitiethoadons(chitiethoadon entity)
		{
			this.SendPropertyChanging();
			entity.hoadon1 = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.chitiethoadon")]
	public partial class chitiethoadon : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _hoadon;
		
		private string _sanpham;
		
		private System.Nullable<int> _soluong;
		
		private EntityRef<hoadon> _hoadon1;
		
		private EntityRef<sanpham> _sanpham1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnhoadonChanging(string value);
    partial void OnhoadonChanged();
    partial void OnsanphamChanging(string value);
    partial void OnsanphamChanged();
    partial void OnsoluongChanging(System.Nullable<int> value);
    partial void OnsoluongChanged();
    #endregion
		
		public chitiethoadon()
		{
			this._hoadon1 = default(EntityRef<hoadon>);
			this._sanpham1 = default(EntityRef<sanpham>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hoadon", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string hoadon
		{
			get
			{
				return this._hoadon;
			}
			set
			{
				if ((this._hoadon != value))
				{
					if (this._hoadon1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnhoadonChanging(value);
					this.SendPropertyChanging();
					this._hoadon = value;
					this.SendPropertyChanged("hoadon");
					this.OnhoadonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sanpham", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string sanpham
		{
			get
			{
				return this._sanpham;
			}
			set
			{
				if ((this._sanpham != value))
				{
					if (this._sanpham1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnsanphamChanging(value);
					this.SendPropertyChanging();
					this._sanpham = value;
					this.SendPropertyChanged("sanpham");
					this.OnsanphamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soluong", DbType="Int")]
		public System.Nullable<int> soluong
		{
			get
			{
				return this._soluong;
			}
			set
			{
				if ((this._soluong != value))
				{
					this.OnsoluongChanging(value);
					this.SendPropertyChanging();
					this._soluong = value;
					this.SendPropertyChanged("soluong");
					this.OnsoluongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="hoadon_chitiethoadon", Storage="_hoadon1", ThisKey="hoadon", OtherKey="mahoadon", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public hoadon hoadon1
		{
			get
			{
				return this._hoadon1.Entity;
			}
			set
			{
				hoadon previousValue = this._hoadon1.Entity;
				if (((previousValue != value) 
							|| (this._hoadon1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._hoadon1.Entity = null;
						previousValue.chitiethoadons.Remove(this);
					}
					this._hoadon1.Entity = value;
					if ((value != null))
					{
						value.chitiethoadons.Add(this);
						this._hoadon = value.mahoadon;
					}
					else
					{
						this._hoadon = default(string);
					}
					this.SendPropertyChanged("hoadon1");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="sanpham_chitiethoadon", Storage="_sanpham1", ThisKey="sanpham", OtherKey="masanpham", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public sanpham sanpham1
		{
			get
			{
				return this._sanpham1.Entity;
			}
			set
			{
				sanpham previousValue = this._sanpham1.Entity;
				if (((previousValue != value) 
							|| (this._sanpham1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._sanpham1.Entity = null;
						previousValue.chitiethoadons.Remove(this);
					}
					this._sanpham1.Entity = value;
					if ((value != null))
					{
						value.chitiethoadons.Add(this);
						this._sanpham = value.masanpham;
					}
					else
					{
						this._sanpham = default(string);
					}
					this.SendPropertyChanged("sanpham1");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.khachhang")]
	public partial class khachhang : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _makhachhang;
		
		private string _tenkhachhang;
		
		private string _ngaysinh;
		
		private string _diachi;
		
		private string _gioitinh;
		
		private string _sodienthoai;
		
		private EntitySet<hoadon> _hoadons;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmakhachhangChanging(string value);
    partial void OnmakhachhangChanged();
    partial void OntenkhachhangChanging(string value);
    partial void OntenkhachhangChanged();
    partial void OnngaysinhChanging(string value);
    partial void OnngaysinhChanged();
    partial void OndiachiChanging(string value);
    partial void OndiachiChanged();
    partial void OngioitinhChanging(string value);
    partial void OngioitinhChanged();
    partial void OnsodienthoaiChanging(string value);
    partial void OnsodienthoaiChanged();
    #endregion
		
		public khachhang()
		{
			this._hoadons = new EntitySet<hoadon>(new Action<hoadon>(this.attach_hoadons), new Action<hoadon>(this.detach_hoadons));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_makhachhang", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string makhachhang
		{
			get
			{
				return this._makhachhang;
			}
			set
			{
				if ((this._makhachhang != value))
				{
					this.OnmakhachhangChanging(value);
					this.SendPropertyChanging();
					this._makhachhang = value;
					this.SendPropertyChanged("makhachhang");
					this.OnmakhachhangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenkhachhang", DbType="NVarChar(50)")]
		public string tenkhachhang
		{
			get
			{
				return this._tenkhachhang;
			}
			set
			{
				if ((this._tenkhachhang != value))
				{
					this.OntenkhachhangChanging(value);
					this.SendPropertyChanging();
					this._tenkhachhang = value;
					this.SendPropertyChanged("tenkhachhang");
					this.OntenkhachhangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngaysinh", DbType="NVarChar(15)")]
		public string ngaysinh
		{
			get
			{
				return this._ngaysinh;
			}
			set
			{
				if ((this._ngaysinh != value))
				{
					this.OnngaysinhChanging(value);
					this.SendPropertyChanging();
					this._ngaysinh = value;
					this.SendPropertyChanged("ngaysinh");
					this.OnngaysinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_diachi", DbType="NVarChar(50)")]
		public string diachi
		{
			get
			{
				return this._diachi;
			}
			set
			{
				if ((this._diachi != value))
				{
					this.OndiachiChanging(value);
					this.SendPropertyChanging();
					this._diachi = value;
					this.SendPropertyChanged("diachi");
					this.OndiachiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gioitinh", DbType="NChar(10)")]
		public string gioitinh
		{
			get
			{
				return this._gioitinh;
			}
			set
			{
				if ((this._gioitinh != value))
				{
					this.OngioitinhChanging(value);
					this.SendPropertyChanging();
					this._gioitinh = value;
					this.SendPropertyChanged("gioitinh");
					this.OngioitinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sodienthoai", DbType="NVarChar(10)")]
		public string sodienthoai
		{
			get
			{
				return this._sodienthoai;
			}
			set
			{
				if ((this._sodienthoai != value))
				{
					this.OnsodienthoaiChanging(value);
					this.SendPropertyChanging();
					this._sodienthoai = value;
					this.SendPropertyChanged("sodienthoai");
					this.OnsodienthoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="khachhang_hoadon", Storage="_hoadons", ThisKey="makhachhang", OtherKey="khachhang")]
		public EntitySet<hoadon> hoadons
		{
			get
			{
				return this._hoadons;
			}
			set
			{
				this._hoadons.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_hoadons(hoadon entity)
		{
			this.SendPropertyChanging();
			entity.khachhang1 = this;
		}
		
		private void detach_hoadons(hoadon entity)
		{
			this.SendPropertyChanging();
			entity.khachhang1 = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.loaisanpham")]
	public partial class loaisanpham : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _maloaisanpham;
		
		private string _tenloaisanpham;
		
		private EntitySet<sanpham> _sanphams;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaloaisanphamChanging(string value);
    partial void OnmaloaisanphamChanged();
    partial void OntenloaisanphamChanging(string value);
    partial void OntenloaisanphamChanged();
    #endregion
		
		public loaisanpham()
		{
			this._sanphams = new EntitySet<sanpham>(new Action<sanpham>(this.attach_sanphams), new Action<sanpham>(this.detach_sanphams));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maloaisanpham", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string maloaisanpham
		{
			get
			{
				return this._maloaisanpham;
			}
			set
			{
				if ((this._maloaisanpham != value))
				{
					this.OnmaloaisanphamChanging(value);
					this.SendPropertyChanging();
					this._maloaisanpham = value;
					this.SendPropertyChanged("maloaisanpham");
					this.OnmaloaisanphamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenloaisanpham", DbType="NVarChar(50)")]
		public string tenloaisanpham
		{
			get
			{
				return this._tenloaisanpham;
			}
			set
			{
				if ((this._tenloaisanpham != value))
				{
					this.OntenloaisanphamChanging(value);
					this.SendPropertyChanging();
					this._tenloaisanpham = value;
					this.SendPropertyChanged("tenloaisanpham");
					this.OntenloaisanphamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="loaisanpham_sanpham", Storage="_sanphams", ThisKey="maloaisanpham", OtherKey="loaisanpham")]
		public EntitySet<sanpham> sanphams
		{
			get
			{
				return this._sanphams;
			}
			set
			{
				this._sanphams.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_sanphams(sanpham entity)
		{
			this.SendPropertyChanging();
			entity.loaisanpham1 = this;
		}
		
		private void detach_sanphams(sanpham entity)
		{
			this.SendPropertyChanging();
			entity.loaisanpham1 = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.nhanvien")]
	public partial class nhanvien : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _manhanvien;
		
		private string _tennhanvien;
		
		private string _ngaysinh;
		
		private string _gioitinh;
		
		private string _diachi;
		
		private string _sodienthoai;
		
		private EntityRef<chamcong> _chamcong;
		
		private EntitySet<hoadon> _hoadons;
		
		private EntitySet<taikhoan> _taikhoans;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmanhanvienChanging(string value);
    partial void OnmanhanvienChanged();
    partial void OntennhanvienChanging(string value);
    partial void OntennhanvienChanged();
    partial void OnngaysinhChanging(string value);
    partial void OnngaysinhChanged();
    partial void OngioitinhChanging(string value);
    partial void OngioitinhChanged();
    partial void OndiachiChanging(string value);
    partial void OndiachiChanged();
    partial void OnsodienthoaiChanging(string value);
    partial void OnsodienthoaiChanged();
    #endregion
		
		public nhanvien()
		{
			this._chamcong = default(EntityRef<chamcong>);
			this._hoadons = new EntitySet<hoadon>(new Action<hoadon>(this.attach_hoadons), new Action<hoadon>(this.detach_hoadons));
			this._taikhoans = new EntitySet<taikhoan>(new Action<taikhoan>(this.attach_taikhoans), new Action<taikhoan>(this.detach_taikhoans));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_manhanvien", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string manhanvien
		{
			get
			{
				return this._manhanvien;
			}
			set
			{
				if ((this._manhanvien != value))
				{
					this.OnmanhanvienChanging(value);
					this.SendPropertyChanging();
					this._manhanvien = value;
					this.SendPropertyChanged("manhanvien");
					this.OnmanhanvienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tennhanvien", DbType="NVarChar(50)")]
		public string tennhanvien
		{
			get
			{
				return this._tennhanvien;
			}
			set
			{
				if ((this._tennhanvien != value))
				{
					this.OntennhanvienChanging(value);
					this.SendPropertyChanging();
					this._tennhanvien = value;
					this.SendPropertyChanged("tennhanvien");
					this.OntennhanvienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngaysinh", DbType="NVarChar(20)")]
		public string ngaysinh
		{
			get
			{
				return this._ngaysinh;
			}
			set
			{
				if ((this._ngaysinh != value))
				{
					this.OnngaysinhChanging(value);
					this.SendPropertyChanging();
					this._ngaysinh = value;
					this.SendPropertyChanged("ngaysinh");
					this.OnngaysinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gioitinh", DbType="NChar(10)")]
		public string gioitinh
		{
			get
			{
				return this._gioitinh;
			}
			set
			{
				if ((this._gioitinh != value))
				{
					this.OngioitinhChanging(value);
					this.SendPropertyChanging();
					this._gioitinh = value;
					this.SendPropertyChanged("gioitinh");
					this.OngioitinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_diachi", DbType="NVarChar(50)")]
		public string diachi
		{
			get
			{
				return this._diachi;
			}
			set
			{
				if ((this._diachi != value))
				{
					this.OndiachiChanging(value);
					this.SendPropertyChanging();
					this._diachi = value;
					this.SendPropertyChanged("diachi");
					this.OndiachiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sodienthoai", DbType="NChar(10)")]
		public string sodienthoai
		{
			get
			{
				return this._sodienthoai;
			}
			set
			{
				if ((this._sodienthoai != value))
				{
					this.OnsodienthoaiChanging(value);
					this.SendPropertyChanging();
					this._sodienthoai = value;
					this.SendPropertyChanged("sodienthoai");
					this.OnsodienthoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="nhanvien_chamcong", Storage="_chamcong", ThisKey="manhanvien", OtherKey="manhanvien", IsUnique=true, IsForeignKey=false)]
		public chamcong chamcong
		{
			get
			{
				return this._chamcong.Entity;
			}
			set
			{
				chamcong previousValue = this._chamcong.Entity;
				if (((previousValue != value) 
							|| (this._chamcong.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._chamcong.Entity = null;
						previousValue.nhanvien = null;
					}
					this._chamcong.Entity = value;
					if ((value != null))
					{
						value.nhanvien = this;
					}
					this.SendPropertyChanged("chamcong");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="nhanvien_hoadon", Storage="_hoadons", ThisKey="manhanvien", OtherKey="nhanvienban")]
		public EntitySet<hoadon> hoadons
		{
			get
			{
				return this._hoadons;
			}
			set
			{
				this._hoadons.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="nhanvien_taikhoan", Storage="_taikhoans", ThisKey="manhanvien", OtherKey="manhanvien")]
		public EntitySet<taikhoan> taikhoans
		{
			get
			{
				return this._taikhoans;
			}
			set
			{
				this._taikhoans.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_hoadons(hoadon entity)
		{
			this.SendPropertyChanging();
			entity.nhanvien = this;
		}
		
		private void detach_hoadons(hoadon entity)
		{
			this.SendPropertyChanging();
			entity.nhanvien = null;
		}
		
		private void attach_taikhoans(taikhoan entity)
		{
			this.SendPropertyChanging();
			entity.nhanvien = this;
		}
		
		private void detach_taikhoans(taikhoan entity)
		{
			this.SendPropertyChanging();
			entity.nhanvien = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.sanpham")]
	public partial class sanpham : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _masanpham;
		
		private string _tensanpham;
		
		private System.Nullable<decimal> _giathanh;
		
		private System.Nullable<int> _soluongcon;
		
		private string _loaisanpham;
		
		private EntitySet<chitiethoadon> _chitiethoadons;
		
		private EntityRef<loaisanpham> _loaisanpham1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmasanphamChanging(string value);
    partial void OnmasanphamChanged();
    partial void OntensanphamChanging(string value);
    partial void OntensanphamChanged();
    partial void OngiathanhChanging(System.Nullable<decimal> value);
    partial void OngiathanhChanged();
    partial void OnsoluongconChanging(System.Nullable<int> value);
    partial void OnsoluongconChanged();
    partial void OnloaisanphamChanging(string value);
    partial void OnloaisanphamChanged();
    #endregion
		
		public sanpham()
		{
			this._chitiethoadons = new EntitySet<chitiethoadon>(new Action<chitiethoadon>(this.attach_chitiethoadons), new Action<chitiethoadon>(this.detach_chitiethoadons));
			this._loaisanpham1 = default(EntityRef<loaisanpham>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_masanpham", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string masanpham
		{
			get
			{
				return this._masanpham;
			}
			set
			{
				if ((this._masanpham != value))
				{
					this.OnmasanphamChanging(value);
					this.SendPropertyChanging();
					this._masanpham = value;
					this.SendPropertyChanged("masanpham");
					this.OnmasanphamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tensanpham", DbType="NVarChar(50)")]
		public string tensanpham
		{
			get
			{
				return this._tensanpham;
			}
			set
			{
				if ((this._tensanpham != value))
				{
					this.OntensanphamChanging(value);
					this.SendPropertyChanging();
					this._tensanpham = value;
					this.SendPropertyChanged("tensanpham");
					this.OntensanphamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_giathanh", DbType="Money")]
		public System.Nullable<decimal> giathanh
		{
			get
			{
				return this._giathanh;
			}
			set
			{
				if ((this._giathanh != value))
				{
					this.OngiathanhChanging(value);
					this.SendPropertyChanging();
					this._giathanh = value;
					this.SendPropertyChanged("giathanh");
					this.OngiathanhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soluongcon", DbType="Int")]
		public System.Nullable<int> soluongcon
		{
			get
			{
				return this._soluongcon;
			}
			set
			{
				if ((this._soluongcon != value))
				{
					this.OnsoluongconChanging(value);
					this.SendPropertyChanging();
					this._soluongcon = value;
					this.SendPropertyChanged("soluongcon");
					this.OnsoluongconChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_loaisanpham", DbType="NChar(10)")]
		public string loaisanpham
		{
			get
			{
				return this._loaisanpham;
			}
			set
			{
				if ((this._loaisanpham != value))
				{
					if (this._loaisanpham1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnloaisanphamChanging(value);
					this.SendPropertyChanging();
					this._loaisanpham = value;
					this.SendPropertyChanged("loaisanpham");
					this.OnloaisanphamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="sanpham_chitiethoadon", Storage="_chitiethoadons", ThisKey="masanpham", OtherKey="sanpham")]
		public EntitySet<chitiethoadon> chitiethoadons
		{
			get
			{
				return this._chitiethoadons;
			}
			set
			{
				this._chitiethoadons.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="loaisanpham_sanpham", Storage="_loaisanpham1", ThisKey="loaisanpham", OtherKey="maloaisanpham", IsForeignKey=true)]
		public loaisanpham loaisanpham1
		{
			get
			{
				return this._loaisanpham1.Entity;
			}
			set
			{
				loaisanpham previousValue = this._loaisanpham1.Entity;
				if (((previousValue != value) 
							|| (this._loaisanpham1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._loaisanpham1.Entity = null;
						previousValue.sanphams.Remove(this);
					}
					this._loaisanpham1.Entity = value;
					if ((value != null))
					{
						value.sanphams.Add(this);
						this._loaisanpham = value.maloaisanpham;
					}
					else
					{
						this._loaisanpham = default(string);
					}
					this.SendPropertyChanged("loaisanpham1");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_chitiethoadons(chitiethoadon entity)
		{
			this.SendPropertyChanging();
			entity.sanpham1 = this;
		}
		
		private void detach_chitiethoadons(chitiethoadon entity)
		{
			this.SendPropertyChanging();
			entity.sanpham1 = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.taikhoan")]
	public partial class taikhoan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _mataikhoan;
		
		private string _manhanvien;
		
		private string _matkhau;
		
		private EntityRef<nhanvien> _nhanvien;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmataikhoanChanging(string value);
    partial void OnmataikhoanChanged();
    partial void OnmanhanvienChanging(string value);
    partial void OnmanhanvienChanged();
    partial void OnmatkhauChanging(string value);
    partial void OnmatkhauChanged();
    #endregion
		
		public taikhoan()
		{
			this._nhanvien = default(EntityRef<nhanvien>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mataikhoan", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string mataikhoan
		{
			get
			{
				return this._mataikhoan;
			}
			set
			{
				if ((this._mataikhoan != value))
				{
					this.OnmataikhoanChanging(value);
					this.SendPropertyChanging();
					this._mataikhoan = value;
					this.SendPropertyChanged("mataikhoan");
					this.OnmataikhoanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_manhanvien", DbType="NChar(10)")]
		public string manhanvien
		{
			get
			{
				return this._manhanvien;
			}
			set
			{
				if ((this._manhanvien != value))
				{
					if (this._nhanvien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmanhanvienChanging(value);
					this.SendPropertyChanging();
					this._manhanvien = value;
					this.SendPropertyChanged("manhanvien");
					this.OnmanhanvienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_matkhau", DbType="NChar(10)")]
		public string matkhau
		{
			get
			{
				return this._matkhau;
			}
			set
			{
				if ((this._matkhau != value))
				{
					this.OnmatkhauChanging(value);
					this.SendPropertyChanging();
					this._matkhau = value;
					this.SendPropertyChanged("matkhau");
					this.OnmatkhauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="nhanvien_taikhoan", Storage="_nhanvien", ThisKey="manhanvien", OtherKey="manhanvien", IsForeignKey=true)]
		public nhanvien nhanvien
		{
			get
			{
				return this._nhanvien.Entity;
			}
			set
			{
				nhanvien previousValue = this._nhanvien.Entity;
				if (((previousValue != value) 
							|| (this._nhanvien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._nhanvien.Entity = null;
						previousValue.taikhoans.Remove(this);
					}
					this._nhanvien.Entity = value;
					if ((value != null))
					{
						value.taikhoans.Add(this);
						this._manhanvien = value.manhanvien;
					}
					else
					{
						this._manhanvien = default(string);
					}
					this.SendPropertyChanged("nhanvien");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
